# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 18:19
from __future__ import unicode_literals

import dhcp.models.shared_network
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4), inventory.models.validation.validate_special_characters])),
                ('address', models.GenericIPAddressField(validators=[inventory.models.validation.ip_validator])),
                ('mac', models.CharField(max_length=255, validators=[dhcp.models.shared_network.validate_characters_mac])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('view_fixedhost', 'Can view fixedhost'),),
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('view_helper', 'Can view helper'),),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(choices=[(b'domain-name', b'domain-name'), (b'domain-name-servers', b'domain-name-servers'), (b'ntp-servers', b'ntp-servers'), (b'netbios-name-servers', b'netbios-name-servers'), (b'dhcp6.domain-search', b'dhcp6.domain-search'), (b'dhcp6.name-servers', b'dhcp6.name-servers'), (b'vendor-encapsulated-options', b'vendor-encapsulated-options')], max_length=255)),
                ('option_value', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('view_option', 'Can view option'),),
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.GenericIPAddressField(blank=True, null=True, unique=True, validators=[inventory.models.validation.ip_validator])),
                ('stop', models.GenericIPAddressField(blank=True, null=True, unique=True, validators=[inventory.models.validation.ip_validator])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('view_pool', 'Can view pool'),),
            },
        ),
        migrations.CreateModel(
            name='SharedNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lease_time', models.CharField(choices=[(b'360', b'Eduroam'), (b'3600', b'Pedago\xc5\xa1ko'), (b'3600', b'Administrativno')], max_length=10)),
                ('default_lease_time', models.CharField(choices=[(b'360', b'Eduroam'), (b'3600', b'Pedago\xc5\xa1ko'), (b'3600', b'Administrativno')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('view_sharednetwork', 'Can view shared network'),),
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True, validators=[inventory.models.validation.ip_validator])),
                ('router', models.GenericIPAddressField(unique=True, validators=[inventory.models.validation.ip_validator])),
                ('prefix', models.IntegerField(default=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcp.SharedNetwork')),
            ],
            options={
                'permissions': (('view_subnet', 'Can view subnet'),),
            },
        ),
    ]
