# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('dhcp', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednetwork',
            name='network',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Network'),
        ),
        migrations.AddField(
            model_name='sharednetwork',
            name='options',
            field=models.ManyToManyField(blank=True, to='dhcp.Option'),
        ),
        migrations.AddField(
            model_name='pool',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcp.Subnet'),
        ),
        migrations.AddField(
            model_name='option',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='helper',
            name='addresses',
            field=models.ManyToManyField(to='inventory.Address'),
        ),
        migrations.AddField(
            model_name='helper',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Interface'),
        ),
        migrations.AddField(
            model_name='fixedhost',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcp.Subnet'),
        ),
        migrations.AlterUniqueTogether(
            name='fixedhost',
            unique_together=set([('name', 'subnet'), ('mac', 'subnet'), ('subnet', 'address')]),
        ),
    ]
